# Generated by Django 5.1.6 on 2025-03-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
    ]
